core:
  #No routes needed
  resource: "@CoreBundle/Controller/"
  type:     annotation
  prefix:   /core

api:
  #Routing for the main REST API
  resource: "@ApiBundle/Resources/config/routing.yml"
  prefix:   /

app:
  resource: "@AppBundle/Controller/"
  type:     annotation
  prefix:   /
